# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_MT7932_FULLMAC) += mt7932-fullmac.o
mt7932-fullmac-y := mt7932.o recovery.o calibration_transport.o data.o frontend.o link.o startup.o reset.o lifecycle.o station.o power.o station_query.o
