# SPDX-License-Identifier: GPL-2.0-only

snd-soc-aop-y		:= aop_audio.o
obj-$(CONFIG_SND_SOC_APPLE_AOP_AUDIO)	+= snd-soc-aop.o

snd-soc-t8140-aop-audio-y	:= t8140_aop_audio.o
obj-$(CONFIG_SND_SOC_APPLE_T8140_AOP_AUDIO)	+= snd-soc-t8140-aop-audio.o

snd-soc-apple-mca-y	:= mca.o

obj-$(CONFIG_SND_SOC_APPLE_MCA)	+= snd-soc-apple-mca.o

snd-soc-macaudio-objs	:= macaudio.o

obj-$(CONFIG_SND_SOC_APPLE_MACAUDIO)	+= snd-soc-macaudio.o
