"""The M3 Air GPU experiment's scripts (tools/aurora-sep/air-gpu) and --m3-gpu-experiment.

Every script is sourced with AIR_GPU_SOURCE_ONLY=1 and pointed at a fake Mac in a temporary
directory: device tree, EFI variables (plain files), an EFI partition with Limine, limine.conf,
the installed UKI and U-Boot's variable file. Nothing here needs root or an Apple Mac.

OneShotTest covers air-gpu-oneshot.sh: arming one boot, Limine consuming it, --disarm, --check,
and every refusal (each leaves every file as it was). CollectVerdictTest feeds air-gpu-collect.sh
kernel logs for each verdict, CollectRunTest runs it end to end, and JobTest covers
air-gpu-job.sh's checks, records and time limit with a fake python3 (JobVulkanTest runs the real
Vulkan job when AIR_GPU_TEST_VULKAN=1 and a Vulkan device is present). GpuExperimentFlagTest
runs the installer with --m3-gpu-experiment on the fake Mac of test_m3_flow.
"""
from pathlib import Path
import hashlib
import os
import re
import shutil
import subprocess
import tarfile
import tempfile
import time
import unittest

HERE = Path(__file__).resolve().parent
TOOLS = HERE.parent / "air-gpu"
ONESHOT = TOOLS / "air-gpu-oneshot.sh"
COLLECT = TOOLS / "air-gpu-collect.sh"
JOB = TOOLS / "air-gpu-job.sh"
# The kernel tree this installer ships with, when the T8122 start experiment is in it.
KERNEL_ASAHI = HERE.parents[2] / "drivers/gpu/drm/asahi"

BLI = "4a67b082-0a4c-41cf-b6c7-440b29bb8c4f"
UBOOT = "b2ac5fc9-92b7-4acd-aeac-11e818c3130c"
GLOBAL = "8be4df61-93ca-11d2-aa0d-00e098032b8c"
KREL = "7.1.12-2-12.1-sep-ARCH"
CMDLINE = ("root=UUID=4f4d5801-524f-4f54-8000-000000000001 rw rootflags=subvol=@ zswap.enabled=0 "
           "rootfstype=btrfs quiet loglevel=3 splash")
PARAMS = [b"asahi.t8122_start", b"asahi.t8122_initdata_version", b"asahi.t8122_fender",
          b"asahi.t8122_clkgen", b"asahi.t8122_sgx_setup", b"asahi.t8122_unit_mask_a",
          b"asahi.t8122_unit_mask_b", b"asahi.t8122_pstate_cap", b"asahi.m3_expose",
          b"asahi.m3_timeout_nohang"]
BOARDS = {
    "j613": ["apple,j613", "apple,t8122", "apple,arm-platform"],
    "j615": ["apple,j615", "apple,t8122", "apple,arm-platform"],
    "j504": ["apple,j504", "apple,t8122", "apple,arm-platform"],
    "j516s": ["apple,j516s", "apple,t6030", "apple,arm-platform"],
    "j314s": ["apple,j314s", "apple,t6000", "apple,arm-platform"],
}
MACLAB = ("# maclab: begin. Managed by lab-agent: staged test kernels, booted once via LoaderEntryOneShot.\n"
          "# maclab: end\n")


def utf16z(s):
    return s.encode("utf-16-le") + b"\0\0"


def var(attrs, data):
    return attrs.to_bytes(4, "little") + data


def limine_conf(path, cmdline=CMDLINE, extra="", kver=KREL, top=""):
    return (f"timeout: 3\ndefault_entry: 2\n{top}"
            "/+Omarchy\n"
            "comment: machine-id=x order-priority=50\n"
            "  //linux-aurora\n"
            "  ### This kernel entry is auto-generated by limine-entry-tool\n"
            f"  comment: Kernel version: {kver}\n"
            "  comment: kernel-id=linux-aurora\n"
            "  protocol: efi\n"
            f"  path: {path}\n"
            f"  cmdline: {cmdline}\n"
            f"{extra}"
            "\n/GRUB (M3 bring-up kernels)\n    protocol: efi\n    path: boot():/EFI/grub/grubaa64.efi\n\n"
            + MACLAB)


class FakeMac:
    """The files a script reads and writes on a Mac, in a temporary directory."""

    def __init__(self, tc, board="j613", uki_params=PARAMS, krel=KREL):
        self.tmp = Path(tempfile.mkdtemp())
        tc.addCleanup(shutil.rmtree, self.tmp)
        for d in ("dt/soc/gpu@292400000", "efivars", "esp/EFI/BOOT", "esp/EFI/Linux", "state", "run",
                  "bin", "etc", "home"):
            (self.tmp / d).mkdir(parents=True)
        self.dt = self.tmp / "dt"
        self.efivars = self.tmp / "efivars"
        self.esp = self.tmp / "esp"
        self.conf = self.esp / "limine.conf"
        self.varfile = self.esp / "ubootefi.var"
        self.uki = self.esp / "EFI/Linux/omarchy_linux-aurora.efi"
        self.state = self.tmp / "state"
        self.cmdline = self.tmp / "run/cmdline"
        self.cmdline.write_text(CMDLINE + "\n")
        self.board(board)
        gpu = self.dt / "soc/gpu@292400000"
        (gpu / "compatible").write_bytes(b"apple,agx-t8122\0" if board != "j516s" else b"apple,agx-t6030\0")
        (gpu / "status").write_bytes(b"okay\0")
        (self.esp / "EFI/BOOT/BOOTAA64.EFI").write_bytes(b"\x7fLIMINE...limine.conf...\0")
        self.uki.write_bytes(b"MZ" + b"\0".join(uki_params) + b"\0" + krel.encode() + b"\0tail")
        self.path = "boot():/EFI/Linux/omarchy_linux-aurora.efi#" + self.b2(self.uki)
        self.conf.write_text(limine_conf(self.path))
        self.setvar("LoaderInfo", BLI, var(6, utf16z("Limine 12.9.1")))
        self.setvar("LoaderEntrySelected", BLI, var(6, utf16z("Omarchy.linux-aurora")))
        self.setvar("RTStorageVolatile", UBOOT, var(6, b"ubootefi.var\0"))
        self.setvar("VarToFile", UBOOT, var(6, b"\0" * 8 + b"UbEfiVa\0"))
        self.setvar("SecureBoot", GLOBAL, var(6, b"\0"))
        self.varfile.write_bytes(self.store())
        (self.tmp / "etc/limine").write_text('ENABLE_UKI=yes\nKERNEL_CMDLINE[default]="x"\n')
        logger = self.tmp / "bin/logger"
        logger.write_text(f'#!/bin/sh\necho "$*" >>"{self.tmp}/logger.log"\n')
        logger.chmod(0o755)

    @staticmethod
    def b2(p):
        return hashlib.blake2b(p.read_bytes()).hexdigest()

    def board(self, board):
        (self.dt / "compatible").write_bytes(b"".join(c.encode() + b"\0" for c in BOARDS[board]))

    def setvar(self, name, guid, data):
        (self.efivars / f"{name}-{guid}").write_bytes(data)

    def oneshot_var(self):
        p = self.efivars / f"LoaderEntryOneShot-{BLI}"
        return p.read_bytes() if p.exists() else None

    def store(self):
        """U-Boot's store as VarToFile gives it: a header, then each variable's UTF-16 name, its
        terminator and its data (U-Boot's entry header is left out)."""
        out = b"\0" * 8 + b"UbEfiVa\0"
        for f in sorted(self.efivars.iterdir()):
            if f.name.startswith("VarToFile-"):
                continue
            out += b"HDR" + utf16z(f.name.rsplit("-", 5)[0]) + f.read_bytes()[4:]
        return out

    def limine_boots(self):
        """What Limine and U-Boot do at the next boot: read and delete the one-shot, record the
        entry booted as LimineLastBootedEntry, save the store."""
        armed = self.oneshot_var()
        p = self.efivars / f"LoaderEntryOneShot-{BLI}"
        if p.exists():
            p.unlink()
        booted = armed[4:].decode("utf-16-le").rstrip("\0") if armed else "Omarchy/linux-aurora"
        # Limine stores this one as ASCII (seen in the m3pro's ubootefi.var).
        self.setvar("LimineLastBootedEntry", "513ee0d0-6e43-cb05-b272-f146a2fcb88a", var(7, booted.encode() + b"\0"))
        self.varfile.write_bytes(self.store())
        return armed

    def snapshot(self):
        return {str(p.relative_to(self.tmp)): p.read_bytes()
                for p in sorted(self.tmp.rglob("*")) if p.is_file() and p.name != "logger.log"}

    def prelude(self, script, root=True):
        return f"""
set -euo pipefail
AIR_GPU_SOURCE_ONLY=1 source '{script}'
DT='{self.dt}'
EFIVARS='{self.efivars}'
ESP='{self.esp}'
STATE_DIR='{self.state}'
CMDLINE='{self.cmdline}'
LOCKS='{self.tmp}/run/boot-partition.lock {self.tmp}/run/limine-global.lock'
LIMINE_DEFAULTS='{self.tmp}/etc/limine'
KREL='{KREL}'
is_root() {{ {'true' if root else 'false'}; }}
# U-Boot regenerates VarToFile from its store; here it is built from the variable files, as
# FakeMac.store lays them out.
uboot_store() {{
  printf '\\0\\0\\0\\0\\0\\0\\0\\0UbEfiVa\\0'
  local f n
  for f in "$EFIVARS"/*; do
    [[ ${{f##*/}} == VarToFile-* ]] && continue
    n=${{f##*/}}; n=${{n%-*-*-*-*-*}}
    printf 'HDR'; printf '%s' "$n" | iconv -f UTF-8 -t UTF-16LE; printf '\\0\\0'; tail -c +5 "$f"
  done
}}
"""

    def run(self, script, body, root=True, check=False):
        env = {**os.environ, "PATH": f"{self.tmp}/bin:{os.environ['PATH']}"}
        proc = subprocess.run(["bash", "-c", self.prelude(script, root) + body], capture_output=True,
                              text=True, env=env)
        if check and proc.returncode != 0:
            raise AssertionError(proc.stdout + proc.stderr)
        return proc


class OneShotTest(unittest.TestCase):
    def setUp(self):
        if not shutil.which("b2sum") or not shutil.which("iconv") or not shutil.which("flock"):
            self.skipTest("b2sum, iconv and flock are needed")
        self.mac = FakeMac(self)

    def oneshot(self, *args, root=True, check=False):
        return self.mac.run(ONESHOT, "main " + " ".join(f"'{a}'" for a in args), root=root, check=check)

    def armed_block(self):
        text = self.mac.conf.read_text()
        m = re.search(r"^# >>> air-gpu-oneshot:.*?^# <<< air-gpu-oneshot$", text, re.M | re.S)
        return m.group(0) if m else None

    # Arming one boot

    def test_arm_consume_disarm(self):
        before = self.mac.conf.read_bytes()
        proc = self.oneshot("t8122_pstate_cap=1", "asahi.t8122_clkgen=e1c", check=True)
        self.assertIn("armed one boot", proc.stdout)
        self.assertIn("every boot after it is the normal entry", proc.stdout)
        block = self.armed_block()
        self.assertIsNotNone(block)
        lines = block.splitlines()
        self.assertEqual(lines[1], "/air-gpu-oneshot")
        self.assertIn("    protocol: efi", lines)
        self.assertIn(f"    path: {self.mac.path}", lines)
        cmd = next(l for l in lines if l.startswith("    cmdline: "))[len("    cmdline: "):]
        self.assertTrue(cmd.startswith(CMDLINE + " asahi.t8122_start=1 asahi.t8122_pstate_cap=1 "
                                       "asahi.t8122_clkgen=e1c panic=10 air_gpu.oneshot="), cmd)
        # The normal entry, the default and everything else stay as they were.
        text = self.mac.conf.read_text()
        self.assertTrue(text.startswith(before.decode().rstrip("\n")), text)
        self.assertIn("default_entry: 2\n", text)
        self.assertIn(MACLAB, text)
        # The one-shot: non-volatile, boot and runtime access, the entry's name; and on the ESP.
        self.assertEqual(self.mac.oneshot_var(), var(7, utf16z("air-gpu-oneshot")))
        self.assertIn(utf16z("LoaderEntryOneShot") + utf16z("air-gpu-oneshot"), self.mac.varfile.read_bytes())
        self.assertTrue((self.mac.state / "armed").exists())
        self.assertIn("armed one boot", (self.mac.tmp / "logger.log").read_text())

        # Limine reads and deletes it: the boot after the armed one is the normal entry.
        self.assertEqual(self.mac.limine_boots(), var(7, utf16z("air-gpu-oneshot")))
        status = self.oneshot("--status", check=True).stdout
        self.assertIn("one-shot variable: not set", status)
        self.assertIn("does not name air-gpu-oneshot", status)
        # Limine recorded the armed entry as the last booted one; that is not an armed one-shot.
        self.assertIn(b"air-gpu-oneshot\0", self.mac.varfile.read_bytes())

        proc = self.oneshot("--disarm", check=True)
        self.assertIn("removed the air-gpu-oneshot entry", proc.stdout)
        self.assertEqual(self.mac.conf.read_bytes(), before)

    def test_disarm_before_the_boot(self):
        before = self.mac.conf.read_bytes()
        store = self.mac.varfile.read_bytes()
        self.oneshot("start", check=True)
        proc = self.oneshot("--disarm", check=True)
        self.assertIn("cleared the one-shot", proc.stdout)
        self.assertIsNone(self.mac.oneshot_var())
        self.assertEqual(self.mac.conf.read_bytes(), before)
        self.assertEqual(self.mac.varfile.read_bytes(), store)
        self.assertNotIn(b"air-gpu-oneshot", self.mac.varfile.read_bytes().replace(b"\0", b""))

    def test_rearming_replaces_the_entry(self):
        self.oneshot("start", check=True)
        self.mac.limine_boots()
        self.oneshot("t8122_fender=adt", check=True)
        text = self.mac.conf.read_text()
        self.assertEqual(text.count("/air-gpu-oneshot\n"), 1)
        self.assertIn("asahi.t8122_fender=adt", self.armed_block())

    def test_start_alone(self):
        self.oneshot("start", check=True)
        cmd = re.search(r"^    cmdline: (.*)$", self.armed_block(), re.M).group(1)
        self.assertEqual([w for w in cmd.split() if w.startswith("asahi.")], ["asahi.t8122_start=1"])

    def test_knobs_on_the_normal_cmdline_are_replaced(self):
        self.mac.conf.write_text(limine_conf(self.mac.path, CMDLINE + " asahi.t8122_pstate_cap=5 asahi.m3_expose=0"))
        self.oneshot("t8122_pstate_cap=1", "m3_expose=1", check=True)
        cmd = re.search(r"^    cmdline: (.*)$", self.armed_block(), re.M).group(1).split()
        self.assertEqual([w for w in cmd if w.startswith("asahi.")],
                         ["asahi.t8122_start=1", "asahi.t8122_pstate_cap=1", "asahi.m3_expose=1"])

    def test_check_changes_nothing(self):
        before = self.mac.snapshot()
        proc = self.oneshot("--check", "t8122_sgx_setup=t6030", check=True)
        self.assertIn("check passed", proc.stdout)
        self.assertIn("asahi.t8122_sgx_setup=t6030", proc.stdout)
        self.assertEqual(self.mac.snapshot(), before)
        self.assertFalse((self.mac.tmp / "logger.log").exists())

    def test_list_knobs(self):
        out = self.oneshot("--list-knobs", check=True).stdout
        for p in PARAMS:
            self.assertIn(p.decode()[len("asahi."):], out)

    def test_rehearsal_on_an_m3_pro(self):
        self.mac.board("j516s")
        proc = self.oneshot("--allow-test-on-m3pro", "start", check=True)
        self.assertIn("rehearsal on an M3 Pro", proc.stdout)
        self.assertIn("armed one boot", proc.stdout)

    def test_rehearsal_on_a_kernel_without_the_knobs(self):
        # 12.0 on the m3pro: the boot mechanics can still be rehearsed.
        self.mac = FakeMac(self, board="j516s", uki_params=[b"asahi.m3_expose"])
        proc = self.oneshot("--allow-test-on-m3pro", "start", check=True)
        self.assertIn("has no asahi.t8122_start parameter; the rehearsal boot ignores it", proc.stdout)

    # Refusals: each one changes nothing

    def assert_refused(self, why, *args, root=True):
        before = self.mac.snapshot()
        proc = self.oneshot(*args, root=root)
        self.assertNotEqual(proc.returncode, 0, proc.stdout)
        self.assertIn("refused:", proc.stderr)
        self.assertIn(why, proc.stderr)
        self.assertIn("Nothing was changed.", proc.stderr)
        self.assertEqual(self.mac.snapshot(), before)
        self.assertIsNone(self.armed_block())

    def test_refuses_other_macs(self):
        for board, why in [("j516s", "--allow-test-on-m3pro runs the rehearsal"),
                           ("j504", "not an M3 MacBook Air"), ("j314s", "not an M3 MacBook Air")]:
            with self.subTest(board=board):
                self.mac.board(board)
                self.assert_refused(why, "start")
        self.mac.board("j314s")
        self.assert_refused("not an M3 MacBook Air", "--allow-test-on-m3pro", "start")

    def test_refuses_without_root(self):
        self.assert_refused("run as root", "start", root=False)

    def test_refuses_bad_knobs(self):
        for args, why in [(["bogus=1"], 'unknown knob "bogus"'),
                          (["t8122_pstate_cap=6"], "takes"),   # K1 bounds the cap to 1..5
                          (["t8122_pstate_cap=16"], "takes"),
                          (["t8122_clkgen=e2c"], "takes e1c|e5c|none"), (["t8122_start=0"], "takes 1"),
                          (["t8122_unit_mask_a=0x700000003"], "outside what the kernel accepts"),
                          (["t8122_unit_mask_b=0x8"], "takes"),
                          (["t8122_initdata_version=0"], "takes"),   # leading-zero / zero both fail the regex now
                          (["t8122_initdata_version=09"], "takes"),
                          (["t8122_initdata_version=18446744073709551616"], "outside what the kernel accepts"),
                          (["t8122_fender=rule", "t8122_fender=adt"], "given twice"),
                          (["pstate"], "is not a knob=value"), ([], "say what to arm")]:
            with self.subTest(args=args):
                self.assert_refused(why, *args)

    def test_accepts_the_largest_u64_initdata(self):
        proc = self.oneshot("t8122_initdata_version=18446744073709551615", check=True)
        self.assertIn("asahi.t8122_initdata_version=18446744073709551615", self.armed_block())

    def test_refuses_a_knob_the_kernel_lacks(self):
        self.mac = FakeMac(self, uki_params=[p for p in PARAMS if p != b"asahi.t8122_clkgen"])
        self.assert_refused("has no asahi.t8122_clkgen parameter", "t8122_clkgen=none")

    def test_refuses_unsafe_limine_settings(self):
        cases = [
            ("remember_last_entry: yes", lambda: self.mac.conf.write_text(
                limine_conf(self.mac.path, top="remember_last_entry: yes\n"))),
            ("2 //linux-aurora entries", lambda: self.mac.conf.write_text(
                limine_conf(self.mac.path, extra=f"  //linux-aurora\n  protocol: efi\n  path: {self.mac.path}\n"))),
            ("already sets asahi.t8122_start", lambda: self.mac.conf.write_text(
                limine_conf(self.mac.path, CMDLINE + " asahi.t8122_start=1"))),
            ("measures BLAKE2b", lambda: self.mac.uki.write_bytes(self.mac.uki.read_bytes() + b"x")),
            ("Reboot into the installed kernel first", lambda: self.mac.conf.write_text(
                limine_conf(self.mac.path, kver="7.1.12-2-12.0-sep-ARCH"))),
            ("is not Limine", lambda: (self.mac.esp / "EFI/BOOT/BOOTAA64.EFI").write_bytes(b"GRUB")),
            ("ENABLE_ENROLL_LIMINE_CONFIG=yes", lambda: (self.mac.tmp / "etc/limine").write_text(
                'ENABLE_ENROLL_LIMINE_CONFIG="yes"\n')),
            ("has a config hash enrolled", lambda: (self.mac.esp / "EFI/BOOT/BOOTAA64.EFI").write_bytes(
                b"\x7fLIMINE...limine.conf...++CONFIG_B2SUM_SIGNATURE++" + b"a" * 128)),
            ("with no air-gpu-oneshot markers around it", lambda: self.mac.conf.write_text(
                limine_conf(self.mac.path) + f"\n/{'air-gpu-oneshot'}\n    protocol: efi\n    path: x\n")),
            ("Secure Boot is on", lambda: self.mac.setvar("SecureBoot", GLOBAL, var(6, b"\1"))),
            ("did not report itself as Limine", lambda: self.mac.setvar(
                "LoaderInfo", BLI, var(6, utf16z("systemd-boot 258")))),
            ("another one-shot boot is armed (maclab-j1)", lambda: self.mac.setvar(
                "LoaderEntryOneShot", BLI, var(7, utf16z("maclab-j1")))),
            ("VarToFile is missing", lambda: (self.mac.efivars / f"VarToFile-{UBOOT}").unlink()),
            ("has quotes", lambda: self.mac.conf.write_text(
                limine_conf(self.mac.path, CMDLINE + ' x="a b"'))),
        ]
        for why, breakit in cases:
            with self.subTest(why=why):
                self.mac = FakeMac(self)
                breakit()
                self.assert_refused(why, "start")

    def test_a_store_that_does_not_read_back_is_undone(self):
        # U-Boot's store without the new variable: the arming is undone.
        before = self.mac.conf.read_bytes()
        store = self.mac.varfile.read_bytes()
        proc = self.mac.run(ONESHOT, "uboot_store() { printf '\\0\\0\\0\\0\\0\\0\\0\\0UbEfiVa\\0'; }\nmain start")
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("did not read back from the firmware store", proc.stderr)
        self.assertIsNone(self.mac.oneshot_var())
        self.assertEqual(self.mac.conf.read_bytes(), before)
        self.assertNotIn(b"air-gpu-oneshot", self.mac.varfile.read_bytes().replace(b"\0", b""))
        self.assertEqual(len(self.mac.varfile.read_bytes()), len(b"\0" * 8 + b"UbEfiVa\0"), store)

    def test_disarm_leaves_another_one_shot_alone(self):
        self.mac.setvar("LoaderEntryOneShot", BLI, var(7, utf16z("maclab-j1")))
        proc = self.oneshot("--disarm", check=True)
        self.assertIn("another one-shot is armed (maclab-j1); leaving it alone", proc.stdout)
        self.assertEqual(self.mac.oneshot_var(), var(7, utf16z("maclab-j1")))

    def test_arms_with_an_unenrolled_binary(self):
        # A6: the ++CONFIG_B2SUM_SIGNATURE++ marker followed by 128 zeros is the unenrolled state.
        self.mac.esp.joinpath("EFI/BOOT/BOOTAA64.EFI").write_bytes(
            b"\x7fLIMINE...limine.conf...++CONFIG_B2SUM_SIGNATURE++" + b"0" * 128)
        self.oneshot("start", check=True)
        self.assertIsNotNone(self.armed_block())

    def test_disarm_resaves_after_a_failed_persist(self):
        # A7: the first --disarm clears the RAM variable but persist fails; the second must still
        # save the cleared store, not skip it because the RAM variable is now empty.
        self.oneshot("start", check=True)
        self.assertIn(utf16z("air-gpu-oneshot"), self.mac.store())
        # persist fails: the variable file is not updated, so it still names the entry.
        proc = self.mac.run(ONESHOT, "persist() { return 1; }\nmain --disarm")
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("run --disarm again", proc.stderr)
        self.assertIsNone(self.mac.oneshot_var())                 # RAM variable cleared
        self.assertIn(utf16z("air-gpu-oneshot"), self.mac.varfile.read_bytes())  # file not yet saved
        # The second run completes the save, even though armed_name is now empty.
        proc = self.oneshot("--disarm", check=True)
        self.assertIn("cleared the one-shot", proc.stdout)
        self.assertNotIn(utf16z("air-gpu-oneshot"), self.mac.varfile.read_bytes())

    def test_disarm_removes_a_markerless_entry(self):
        # A11: a tool dropped the markers but left the entry; --disarm removes it.
        self.mac.conf.write_text(limine_conf(self.mac.path) +
                                 "\n/air-gpu-oneshot\n    comment: x\n    protocol: efi\n    path: y\n    cmdline: z\n")
        proc = self.oneshot("--disarm", check=True)
        self.assertIn("removed the air-gpu-oneshot entry", proc.stdout)
        self.assertNotIn("/air-gpu-oneshot", self.mac.conf.read_text())

    @unittest.skipUnless((KERNEL_ASAHI / "t8122_knobs.rs").exists(), "the kernel tree has no T8122 start experiment")
    def test_knobs_are_the_kernels(self):
        src = "".join(p.read_text() for p in KERNEL_ASAHI.glob("*.rs"))
        out = self.oneshot("--list-knobs", check=True).stdout
        for name in re.findall(r"^(t8122_\w+|m3_\w+) ", out, re.M):
            with self.subTest(name=name):
                self.assertTrue(re.search(rf'm3_param!\("{name}"|^\s+{name}: [ui]\d+ {{', src, re.M), name)


# ---- air-gpu-collect.sh ---------------------------------------------------------------------

ARMED = CMDLINE + " asahi.t8122_start=1 air_gpu.oneshot=1007-120000"
DEV = "[    0.10] host kernel: asahi 292400000.gpu: "
PROBE = DEV + "Probing...\n" + DEV + "G15G: T8122 revision 2.0 identity admitted (10 active / 10 slots)\n"
K1_ARMED = DEV + ("M3 G15G start: armed (asahi.t8122_start=1, boot loader handoff admitted): "
                  "initdata_version=0x0c08e21e83800490 fender=0x104000 clkgen=e1c(sgx+0xe1c000,ro) sgx_setup=none "
                  "unit_mask_a=0x700000001 unit_mask_b=0x3 pstate_cap=2\n")
RTKIT = DEV + "RTKit: Initializing (protocol version 12)\n"
PUBLISH = DEV + "M3: publishing owned initdata 0x1234\n"
ACCEPT = DEV + "M3: firmware accepted owned initdata and device controls\n"


def k1(outcome, rest=""):
    return DEV + f"M3 G15G verdict: {outcome}{rest}\n"


RUNNING = PROBE + K1_ARMED + RTKIT + PUBLISH + ACCEPT + k1("firmware-running", ": the firmware accepted the InitData")
REC_PASS = "result=pass\nstage=finished\nreached_gpu=yes\nsubmits=480\nfirst_submit_ms=0.41\ndevice=Apple M3 (G15G C0)\n"


def rec(result, **kw):
    kw.setdefault("reached_gpu", "no" if result in ("no-render-node", "no-device") else "yes")
    return f"result={result}\n" + "".join(f"{k}={v}\n" for k, v in kw.items())


class CollectVerdictTest(unittest.TestCase):
    def setUp(self):
        self.mac = FakeMac(self)

    def verdict(self, log, cmd=ARMED, recs=()):
        # Write each job record, fold them with job_aggregate, then classify (A16: all records).
        logf = self.mac.tmp / "log.txt"
        logf.write_text(log)
        paths = []
        for i, r in enumerate(recs):
            p = self.mac.tmp / f"rec{i}.txt"
            p.write_text(r)
            paths.append(str(p))
        agg = "job_aggregate " + " ".join(f"'{p}'" for p in paths)
        proc = self.mac.run(COLLECT, f"{agg}\nclassify '{logf}' '{cmd}'\necho \"$VERDICT|$REASON\"", check=True)
        return proc.stdout.strip().split("|", 1)

    def test_the_kernels_verdict_lines(self):
        done = k1("job-completed", ": the first compute job finished")
        for log, recs, want, why in [
            (RUNNING, (), "FW-RUNNING", "firmware-running"),
            (RUNNING + done, (REC_PASS,), "JOB-COMPLETED", "runs completed with correct results"),
            # A4: the kernel's job-completed line alone, with no CPU-checked record, is not enough.
            (RUNNING + done, (), "FW-RUNNING", "no air-gpu-job record checked"),
            (RUNNING + k1("job-accepted-never-dispatched", ": start timestamp 0x0"),
             (rec("fence-timeout"),), "JOB-NOT-DISPATCHED", "job-accepted-never-dispatched"),
            # A failure line outranks a completed line (both present).
            (RUNNING + done + k1("job-faulted", " (EIO): y"), (REC_PASS,), "JOB-NOT-DISPATCHED", "job-faulted"),
            (RUNNING + k1("job-retired-without-timestamps", ": z"), (), "JOB-NOT-DISPATCHED",
             "job-retired-without-timestamps"),
            # A4: kernel says completed, but the record's CPU check failed -> not completed.
            (RUNNING + done, (rec("wrong-result", error="bad"),), "JOB-NOT-DISPATCHED", "wrong-result"),
            (RUNNING, (rec("running"),), "JOB-NOT-DISPATCHED", "air-gpu-job"),
            (RUNNING, (rec("no-render-node"),), "FW-RUNNING", "did not reach the GPU"),
            (RUNNING, (REC_PASS,), "JOB-COMPLETED", "air-gpu-job"),
            (PROBE + K1_ARMED + k1("firmware-boot-failed", " (ENODEV): x"), (), "FW-BOOT-FAILED", "firmware-boot-failed"),
            (PROBE + K1_ARMED + RTKIT + k1("driver-refused", " (EINVAL): x"), (), "ARMED-NOT-STARTED", "driver-refused"),
            (PROBE + K1_ARMED + RTKIT + PUBLISH + k1("initdata-rejected", " (ETIMEDOUT): x"), (),
             "INITDATA-REJECTED", "initdata-rejected"),
            # New K1 labels (dbdd6c6f).
            (PROBE + K1_ARMED + RTKIT + k1("publish-failed", " (EIO): x"), (), "FW-BOOT-FAILED", "publish-failed"),
            (PROBE + K1_ARMED + RTKIT + PUBLISH + k1("device-control-failed", " (ETIMEDOUT): x"), (),
             "INITDATA-REJECTED", "device-control-failed"),
            (RUNNING + k1("job-ran-completion-missed", ": GPU start timestamp 0x5"), (), "JOB-NOT-DISPATCHED",
             "job-ran-completion-missed"),
            (RUNNING + k1("job-failed-before-wait", " (EIO): x"), (), "JOB-NOT-DISPATCHED", "job-failed-before-wait"),
            # cap-violated and the check-failed crash variant override a success (A2-adjacent).
            (RUNNING + k1("cap-violated", " (EIO): above the cap"), (REC_PASS,), "FW-CRASHED", "cap-violated"),
            (RUNNING + k1("firmware-running-check-failed", " (EIO): x"), (), "FW-CRASHED",
             "firmware-running-check-failed"),
        ]:
            with self.subTest(want=want, why=why):
                verdict, reason = self.verdict(log, recs=recs)
                self.assertEqual(verdict, want, reason)
                self.assertIn(why, reason)

    def test_crash_after_running_overrides(self):
        # A2: the kernel logged firmware-running (or job-completed), then a crash/fault line.
        crash = DEV + "RTKit: co-processor has crashed\n"
        fault = DEV + "M3 firmware error event 3 bytes=00\n"
        done = k1("job-completed", ": the first compute job finished")
        for log, recs, want, why in [
            (RUNNING + "[ 9.0] host kernel: asahi 292400000.gpu: RTKit: co-processor has crashed\n", (),
             "FW-CRASHED", "crashed or faulted"),
            (RUNNING + done + "[ 9.0] host kernel: asahi 292400000.gpu: RTKit: co-processor has crashed\n",
             (REC_PASS,), "FW-CRASHED", "a job completed, then"),
            (RUNNING + fault, (), "FW-CRASHED", "crashed or faulted"),
            (PROBE + RTKIT + PUBLISH + ACCEPT + crash, (), "FW-CRASHED", "crashed"),  # structural path
        ]:
            with self.subTest(why=why):
                verdict, reason = self.verdict(log, recs=recs)
                self.assertEqual(verdict, want, reason)
                self.assertIn(why, reason)

    def test_a16_any_failed_record_blocks_completed(self):
        # A pass and a fail from the same boot: the fail wins.
        done = k1("job-completed", ": the first compute job finished")
        verdict, reason = self.verdict(RUNNING + done, recs=(rec("wrong-result", error="bad"), REC_PASS))
        self.assertEqual(verdict, "JOB-NOT-DISPATCHED", reason)
        self.assertIn("1 of 2 runs passed", reason)

    def test_a3_stuck_or_killed_job_is_not_fw_running(self):
        # A job that opened the device and then got stuck/killed is a failure, whatever reached_gpu.
        for result in ("stuck", "killed", "device-lost"):
            with self.subTest(result=result):
                verdict, reason = self.verdict(RUNNING, recs=(rec(result, stage="opened-device", reached_gpu="no"),))
                self.assertEqual(verdict, "JOB-NOT-DISPATCHED", reason)
                self.assertIn(result, reason)

    def test_unknown_kernel_verdict(self):
        verdict, _ = self.verdict(RUNNING + k1("something-new", ": x"))
        # firmware-running is still present, so the known label wins; a lone unknown is UNKNOWN.
        self.assertEqual(verdict, "FW-RUNNING")
        verdict, reason = self.verdict(PROBE + K1_ARMED + k1("something-new", ": x"))
        self.assertEqual(verdict, "UNKNOWN", reason)

    def test_refusals_before_the_firmware(self):
        for log, why in [
            ("", "never probed"),
            (PROBE + DEV + "M3 G15G start: refused: asahi.t8122_fender has a value it does not accept "
             "(0x104000 or rule, 0x12c000 or adt); GPU startup disabled\n", "asahi.t8122_fender"),
            (PROBE + DEV + "M3 G15G start: not armed: resource admission refused the GPU\n", "not armed"),
            (PROBE + DEV + "M3 G15G start: refused at the GPU coprocessor setup (RTKit/mailbox) (ENODEV)\n",
             "coprocessor setup"),
            (PROBE + DEV + "M3 G15G: 6 configuration requirements missing; GPU startup disabled\n"
             + DEV + "probe with driver asahi failed with error -19\n", "GPU startup disabled"),
            (PROBE + DEV + "probe with driver asahi failed with error -22\n", "error -22"),
        ]:
            with self.subTest(why=why):
                verdict, reason = self.verdict(log)
                self.assertEqual(verdict, "ARMED-NOT-STARTED", reason)
                self.assertIn(why, reason)
                self.assertNotIn("kernel:", reason)

    def test_without_the_kernels_verdict_lines(self):
        # The M3 Pro rehearsal, or a kernel before them: the structure of the log decides.
        crash = DEV + "RTKit: co-processor has crashed\n"
        for log, recs, want in [
            (PROBE + RTKIT, (), "FW-BOOT-FAILED"),
            (PROBE + RTKIT + crash, (), "FW-BOOT-FAILED"),
            (PROBE + RTKIT + PUBLISH + DEV + "M3 firmware readiness: magic=0x0 runtime=0\n", (), "INITDATA-REJECTED"),
            (PROBE + RTKIT + PUBLISH + ACCEPT, (), "FW-RUNNING"),
            (PROBE + RTKIT + PUBLISH + ACCEPT + crash, (), "FW-CRASHED"),
            (PROBE + RTKIT + PUBLISH + ACCEPT, (REC_PASS,), "JOB-COMPLETED"),
            (PROBE + RTKIT + PUBLISH + ACCEPT + "[ 9.0] host kernel: M3 scheduler: execution failed ETIMEDOUT\n",
             (rec("fence-timeout"),), "JOB-NOT-DISPATCHED"),
            (PROBE + RTKIT + PUBLISH + ACCEPT + crash, (rec("device-lost"),), "JOB-NOT-DISPATCHED"),
        ]:
            with self.subTest(want=want, log=log[-60:]):
                self.assertEqual(self.verdict(log, recs=recs)[0], want)

    def test_not_armed(self):
        self.assertEqual(self.verdict(RUNNING, cmd=CMDLINE)[0], "NOT-ARMED")
        self.assertEqual(self.verdict(RUNNING, cmd=CMDLINE + " asahi.t8122_start=0")[0], "NOT-ARMED")


JOURNALCTL = r"""#!/bin/bash
# The fake journal: $FAKE/journal-<boot>.txt per boot, $FAKE/boots for --list-boots.
b=0
while (($#)); do case $1 in -b) b=$2; shift ;; --list-boots) cat "$FAKE/boots"; exit 0 ;; esac; shift; done
f=$FAKE/journal-$b.txt
[[ -f $f ]] || { echo "-- No entries --"; exit 1; }
if [[ " $* " == *" -o cat "* ]]; then sed -E 's/^\[[^]]*\] [^ ]+ kernel: //' "$f"; else cat "$f"; fi
"""
SMC = """# 3 keys: index key type size flags [value: T* in mC, P* in mW]
   0 #KEY ui32   4 80
   1 PSTR flt    4 85 6060
   2 PZC0 flt    4 85 0
   3 Tg00 flt    4 85 41000
   4 Tg01 flt    4 85 -2800
   5 RMAC ch8*   6 80
"""


class CollectRunTest(unittest.TestCase):
    def setUp(self):
        self.mac = FakeMac(self)
        t = self.mac.tmp
        self.fake = t / "fake"
        self.fake.mkdir()
        self.home = t / "home"
        (t / "bin/journalctl").write_text(JOURNALCTL)
        (t / "bin/dmesg").write_text(f'#!/bin/sh\ncat "{self.fake}/dmesg.txt"\n')
        for f in ("journalctl", "dmesg"):
            (t / "bin" / f).chmod(0o755)
        (t / "debug/macsmc-hwmon").mkdir(parents=True)
        (t / "debug/macsmc-hwmon/keys").write_text(SMC)
        (t / "debug/asahi-m3").mkdir()
        (t / "debug/asahi-m3/progress").write_text("version=1 completed=3 healthy=1\n")
        drv = t / "sys/bus/platform/drivers/asahi"
        drv.mkdir(parents=True)
        (t / "sys/class/drm/renderD128/device").mkdir(parents=True)
        (t / "sys/class/drm/renderD128/device/driver").symlink_to(drv)
        (t / "sys/module/asahi/parameters").mkdir(parents=True)
        (t / "sys/module/asahi/parameters/m3_render_batch_override").write_text("0\n")
        self.boot_id = t / "run/boot_id"
        self.boot_id.write_text("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa\n")
        (self.fake / "boots").write_text("IDX BOOT ID FIRST LAST\n -1 bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb x y\n"
                                         "  0 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa x y\n")
        (self.home / "air-gpu-runs").mkdir()
        self.statedir = t / "state-airgpu"
        self.statedir.mkdir()

    def arm_record(self, oneshot_id):
        (self.statedir / "armed").write_text(f"{oneshot_id} {KREL} cmd air_gpu.oneshot={oneshot_id}\n")

    def collect(self, *args, want_tgz=True):
        t = self.mac.tmp
        body = f"""
DEBUGFS='{t}/debug'
SYS='{t}/sys'
BOOT_ID='{self.boot_id}'
STATE_DIR='{self.statedir}'
user_home() {{ echo '{self.home}'; }}
main {' '.join(args)}
"""
        env_body = f"export FAKE='{self.fake}'\n" + body
        proc = self.mac.run(COLLECT, env_body, check=True)
        tgz = list(self.home.glob("air-gpu-collect-*.tgz"))
        self.assertEqual(len(tgz), 1 if want_tgz else len(tgz), proc.stdout + proc.stderr)
        files = {}
        if tgz:
            with tarfile.open(tgz[0]) as tf:
                files = {m.name.split("/", 1)[1]: tf.extractfile(m).read().decode()
                         for m in tf.getmembers() if m.isfile()}
            tgz[0].unlink()
        return proc, files

    def journal(self, boot, cmd, log):
        (self.fake / f"journal-{boot}.txt").write_text(
            f"[    0.00] host kernel: Linux version {KREL}\n[    0.00] host kernel: Kernel command line: {cmd}\n" + log)

    def test_this_boot(self):
        self.mac.cmdline.write_text(ARMED + "\n")
        self.journal(0, ARMED, RUNNING + k1("job-completed", ": the first compute job finished, GPU timestamps 0x1..0x2")
                     + "[ 3.0] host kernel: usb 1-1: SerialNumber: SECRET123\n"
                     + "[ 3.1] host kernel: brcmfmac: wlan0 address 12:34:56:78:9a:bc\n")
        (self.home / "air-gpu-runs/job-1.txt").write_text("boot_id=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n" + REC_PASS)
        (self.home / "air-gpu-runs/job-0.txt").write_text("boot_id=cccccccccccccccccccccccccccccccc\nresult=pass\n")
        proc, files = self.collect()
        last = proc.stdout.strip().splitlines()[-1]
        self.assertTrue(last.startswith("AIR-GPU VERDICT: JOB-COMPLETED | boot 0 | oneshot 1007-120000 | "), last)
        log = files["kernel-log-boot0.txt"]
        self.assertNotIn("SECRET123", log)
        self.assertNotIn("12:34:56:78:9a:bc", log)
        self.assertIn("xx:xx:xx:xx:xx:xx", log)
        self.assertIn("M3 G15G verdict: job-completed", files["gpu-log.txt"])
        self.assertIn("M3 G15G verdict", files["firmware-log.txt"])
        self.assertEqual(sorted(k for k in files if k.startswith("jobs/")), ["jobs/job-1.txt"])
        smc = files["smc-keys.txt"]
        self.assertIn("Tg00", smc)
        self.assertIn("PSTR", smc)
        self.assertNotIn("RMAC", smc)
        summary = files["summary.txt"]
        self.assertIn("1 of 2 Tg* keys read 10 C or more", summary)
        self.assertIn("PZC0=0", summary)
        self.assertIn("render node: present", summary)
        self.assertIn("kernel armed with: initdata_version=0x0c08e21e83800490", summary)
        self.assertIn("asahi.t8122_start=1", files["asahi-params.txt"])
        self.assertIn("m3_render_batch_override=0", files["asahi-params.txt"])
        self.assertIn("completed=3", files["debugfs-asahi-m3.txt"])
        self.assertIn("LoaderEntryOneShot: not set", files["oneshot.txt"])
        # A15: no hostname in the tgz (uname -srvm, not -a), and no raw coredump.
        import socket
        self.assertNotIn(socket.gethostname(), files["system.txt"])

    def test_a1_judges_by_the_arming_id(self):
        # boot 0 carries a different arming; the last arming is in boot -1. A1 analyses -1, not 0.
        self.mac.cmdline.write_text(CMDLINE + " asahi.t8122_start=1 air_gpu.oneshot=other\n")
        self.journal(0, CMDLINE + " asahi.t8122_start=1 air_gpu.oneshot=other", RUNNING)
        self.journal(-1, ARMED, PROBE + K1_ARMED + k1("firmware-boot-failed", " (ENODEV): x"))
        self.arm_record("1007-120000")
        proc, _ = self.collect()
        last = proc.stdout.strip().splitlines()[-1]
        self.assertTrue(last.startswith("AIR-GPU VERDICT: FW-BOOT-FAILED | boot -1 | oneshot 1007-120000"), last)

    def test_a1_armed_no_log(self):
        # The last arming is in no boot's cmdline and the one-shot was consumed: the armed boot
        # hung before the journal was written. No older boot's result is shown.
        self.mac.cmdline.write_text(CMDLINE + "\n")           # this boot is the normal recovery one
        self.journal(0, CMDLINE, PROBE)
        self.journal(-1, ARMED, RUNNING)                      # an older armed boot, a different id
        self.arm_record("1007-999999")
        proc, files = self.collect()
        last = proc.stdout.strip().splitlines()[-1]
        self.assertTrue(last.startswith("AIR-GPU VERDICT: ARMED-NO-LOG | boot 0 | oneshot 1007-999999"), last)
        self.assertIn("left no kernel log", last)
        # It still gathers this boot's state.
        self.assertIn("Tg00", files["smc-keys.txt"])

    def test_a1_still_armed_not_booted(self):
        # The tester ran collect before rebooting: the one-shot is still set, no boot has the id.
        self.mac.cmdline.write_text(CMDLINE + "\n")
        self.journal(0, CMDLINE, PROBE)
        self.arm_record("1007-777777")
        self.mac.setvar("LoaderEntryOneShot", BLI, var(7, utf16z("air-gpu-oneshot")))
        proc, _ = self.collect()
        self.assertIn("has not run yet", proc.stdout)
        self.assertIn("AIR-GPU VERDICT: NOT-ARMED | boot 0", proc.stdout.strip().splitlines()[-1])

    def test_the_armed_boot_before_this_one(self):
        # No arming record (an older release armed it): fall back to the boot-cmdline heuristic.
        self.journal(0, CMDLINE, PROBE + DEV + "M3 G15G: 6 configuration requirements missing; GPU startup disabled\n")
        self.journal(-1, ARMED, RUNNING)
        (self.home / "air-gpu-runs/job-1.txt").write_text(
            "boot_id=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\nresult=running\nreached_gpu=no\n")
        (self.fake / "dmesg.txt").write_text("[ 0.0] this boot\n")
        proc, files = self.collect()
        last = proc.stdout.strip().splitlines()[-1]
        self.assertTrue(last.startswith("AIR-GPU VERDICT: JOB-NOT-DISPATCHED | boot -1 | oneshot 1007-120000"), last)
        self.assertIn("air-gpu-job", last)
        self.assertIn("kernel-log-boot-1.txt", files)
        self.assertIn("dmesg-boot0.txt", files)
        # Asked for this boot explicitly, it is a normal one.
        proc, _ = self.collect("--boot", "0")
        self.assertIn("AIR-GPU VERDICT: NOT-ARMED | boot 0", proc.stdout.strip().splitlines()[-1])

    def test_a_normal_boot(self):
        self.journal(0, CMDLINE, PROBE)
        proc, files = self.collect()
        self.assertIn("AIR-GPU VERDICT: NOT-ARMED | boot 0 | oneshot none", proc.stdout)

    def test_coredump_left_out_by_default(self):
        self.mac.cmdline.write_text(ARMED + "\n")
        self.journal(0, ARMED, RUNNING)
        dcd = self.mac.tmp / "sys/class/devcoredump/devcd7/data"
        dcd.parent.mkdir(parents=True)
        dcd.write_bytes(b"SECRET-GPU-MEMORY" * 100)
        self.arm_record("1007-120000")
        proc, files = self.collect()
        self.assertIn("devcoredump.txt", files)
        self.assertIn("raw dumps left out", files["devcoredump.txt"])
        self.assertFalse([k for k in files if k.endswith(".bin")])
        # --include-dumps adds the raw bytes for a private hand-over.
        proc, files = self.collect("--include-dumps")
        self.assertTrue([k for k in files if k.endswith(".bin")], list(files))

    def test_dmesg_when_the_journal_lacks_the_boot(self):
        self.mac.cmdline.write_text(ARMED + "\n")
        (self.fake / "dmesg.txt").write_text("[ 0.0] Linux version x\n" + PROBE + K1_ARMED +
                                             k1("firmware-boot-failed", " (ENODEV): x"))
        proc, files = self.collect()
        self.assertIn("AIR-GPU VERDICT: FW-BOOT-FAILED", proc.stdout.strip().splitlines()[-1])


# ---- air-gpu-job.sh -------------------------------------------------------------------------

FAKE_PY = r"""#!/bin/bash
# A stand-in for python3 -c <job> (ignores -I/-c and the args): prints what $FAKE_PY_MODE says
# the job saw, in the order the real job prints its stage markers.
case $FAKE_PY_MODE in
  pass) printf '%s\n' "device=Apple M3 (G15G C0)" opened_device=yes reached_gpu=yes first_submit_ms=0.50 \
    submits=480 verified=480 loop_ms=5000 result=pass; exit 0 ;;
  timeout) printf '%s\n' "device=Apple M3 (G15G C0)" opened_device=yes reached_gpu=yes submits=0 \
    "error=submission 1 did not complete within 2000 ms" result=fence-timeout; exit 3 ;;
  hang) printf '%s\n' "device=Apple M3 (G15G C0)" opened_device=yes reached_gpu=yes; sleep 60 ;;
  stuck-open) printf '%s\n' "device=Apple M3 (G15G C0)" "opened_device=attempting"; sleep 60 ;;
esac
"""


class JobTest(unittest.TestCase):
    def setUp(self):
        self.mac = FakeMac(self)
        t = self.mac.tmp
        self.prefix = t / "prefix"
        (self.prefix / "share/vulkan/icd.d").mkdir(parents=True)
        (self.prefix / "lib").mkdir()
        (self.prefix / "share/vulkan/icd.d/asahi_icd.aarch64.json").write_text("{}")
        drv = t / "sys/bus/platform/drivers/asahi"
        drv.mkdir(parents=True)
        (t / "sys/class/drm/renderD128/device").mkdir(parents=True)
        (t / "sys/class/drm/renderD128/device/driver").symlink_to(drv)
        self.boot_id = t / "run/boot_id"
        self.boot_id.write_text("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa\n")
        self.mac.cmdline.write_text(ARMED + "\n")
        py = t / "bin/python3"
        py.write_text(FAKE_PY)
        py.chmod(0o755)

    def job(self, *args, mode="pass", limit=10):
        t = self.mac.tmp
        body = f"""
export FAKE_PY_MODE={mode}
SYS='{t}/sys'
BOOT_ID='{self.boot_id}'
LIMIT_S={limit}
user_home() {{ echo '{t}/home'; }}
main {' '.join(args)}
"""
        start = time.monotonic()
        proc = self.mac.run(JOB, body)
        return proc, time.monotonic() - start

    def record(self):
        recs = list((self.mac.tmp / "home/air-gpu-runs").glob("job-*.txt"))
        self.assertEqual(len(recs), 1)
        return dict(l.split("=", 1) for l in recs[0].read_text().splitlines() if "=" in l and not l.startswith("---"))

    def test_pass(self):
        proc, _ = self.job(str(self.prefix))
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("air-gpu-job: pass (exit 0", proc.stdout)
        rec = self.record()
        self.assertEqual(rec["boot_id"], "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
        self.assertEqual(rec["oneshot"], "1007-120000")
        self.assertEqual(rec["result"], "pass")
        self.assertEqual(rec["reached_gpu"], "yes")
        self.assertEqual(rec["submits"], "480")
        self.assertEqual(rec["stage"], "finished")
        self.assertIn("start:", (self.mac.tmp / "logger.log").read_text())
        self.assertIn("result: pass", (self.mac.tmp / "logger.log").read_text())

    def test_stuck_before_submitting_records_the_stage(self):
        # A3: the job opened (or was opening) the device, then got stuck; the record says so, so
        # collect never reads it as a clean run.
        proc, _ = self.job(str(self.prefix), mode="stuck-open", limit=2)
        self.assertEqual(proc.returncode, 7)   # killed at the limit
        rec = self.record()
        self.assertEqual(rec["result"], "killed")
        self.assertEqual(rec["stage"], "opening-device")
        self.assertEqual(rec["reached_gpu"], "no")

    def test_refuses_a_symlinked_record_dir(self):
        # A13: the record directory is a symlink to a place the user cannot write; the job refuses
        # rather than force a write (a root run would otherwise follow it).
        ro = self.mac.tmp / "ro"
        ro.mkdir()
        ro.chmod(0o500)
        self.addCleanup(ro.chmod, 0o700)
        (self.mac.tmp / "home/air-gpu-runs").symlink_to(ro / "runs")
        proc, _ = self.job(str(self.prefix))
        self.assertEqual(proc.returncode, 2, proc.stdout + proc.stderr)
        self.assertIn("could not create", proc.stdout)

    def test_the_g15g_prefix_environment(self):
        # The G15G prefix opens a G15G only with both opt-ins, as its bin/g15g-run sets them.
        icd = self.prefix / "share/vulkan/icd.d/asahi_icd.aarch64.json"
        proc = self.mac.run(JOB, f"mesa_env '{self.prefix}' '{icd}'", check=True)
        env = dict(l.split("=", 1) for l in proc.stdout.splitlines())
        self.assertEqual(env["ASAHI_M3_EXPERIMENTAL"], "1")
        self.assertEqual(env["ASAHI_M3_G15G"], "1")
        self.assertEqual(env["MESA_SHADER_CACHE_DISABLE"], "true")
        self.assertEqual(env["VK_DRIVER_FILES"], str(icd))
        self.assertEqual(env["LD_LIBRARY_PATH"], f"{self.prefix}/lib")

    def test_first_submission_never_completes(self):
        proc, _ = self.job(str(self.prefix), mode="timeout")
        self.assertEqual(proc.returncode, 3)
        self.assertEqual(self.record()["result"], "fence-timeout")

    def test_time_limit(self):
        proc, took = self.job(str(self.prefix), mode="hang", limit=2)
        self.assertEqual(proc.returncode, 7, proc.stdout + proc.stderr)
        self.assertLess(took, 6)
        self.assertEqual(self.record()["result"], "killed")

    def test_no_render_node(self):
        (self.mac.tmp / "sys/class/drm/renderD128/device/driver").unlink()
        proc, _ = self.job(str(self.prefix))
        self.assertEqual(proc.returncode, 2)
        self.assertIn("no asahi render node", proc.stdout)
        rec = self.record()
        self.assertEqual(rec["result"], "no-render-node")
        self.assertEqual(rec["reached_gpu"], "no")

    def test_refusals(self):
        two = self.mac.tmp / "two"
        (two / "share/vulkan/icd.d").mkdir(parents=True)
        for n in ("a.json", "b.json"):
            (two / "share/vulkan/icd.d" / n).write_text("{}")
        for args, why in [(["--seconds", "9", str(self.prefix)], "--seconds takes 1 to 8"),
                          (["--seconds", "0", str(self.prefix)], "--seconds takes 1 to 8"),
                          (["--seconds", "x", str(self.prefix)], "--seconds takes 1 to 8"),
                          ([str(self.mac.tmp / "nowhere")], "no Mesa prefix"),
                          ([str(two)], "exactly one Vulkan driver file"),
                          ([str(self.prefix), str(self.prefix)], "one Mesa prefix only")]:
            with self.subTest(args=args):
                proc, _ = self.job(*args)
                self.assertEqual(proc.returncode, 2)
                self.assertIn(why, proc.stdout)
                self.assertFalse((self.mac.tmp / "home/air-gpu-runs").exists())


@unittest.skipUnless(os.environ.get("AIR_GPU_TEST_VULKAN") == "1", "AIR_GPU_TEST_VULKAN=1 runs the real Vulkan job")
class JobVulkanTest(unittest.TestCase):
    """The real job on this machine's Vulkan device, through a prefix holding its driver file."""

    def test_real_job(self):
        icds = sorted(Path("/usr/share/vulkan/icd.d").glob("*.json"))
        drm = [p for p in Path("/sys/class/drm").glob("renderD*") if (p / "device/driver").exists()]
        if not icds or not drm:
            self.skipTest("no Vulkan driver or render node here")
        tmp = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, tmp)
        (tmp / "p/share/vulkan/icd.d").mkdir(parents=True)
        (tmp / "p/lib").mkdir()
        shutil.copy(icds[0], tmp / "p/share/vulkan/icd.d/")
        driver = (drm[0] / "device/driver").resolve().name
        body = f"""
set -euo pipefail
AIR_GPU_SOURCE_ONLY=1 source '{JOB}'
RENDER_DRIVER={driver}
DEVICE_MATCH=""
user_home() {{ echo '{tmp}'; }}
main --seconds 2 '{tmp}/p'
"""
        proc = subprocess.run(["bash", "-c", body], capture_output=True, text=True)
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        rec = next((tmp / "air-gpu-runs").glob("job-*.txt")).read_text()
        self.assertIn("result=pass", rec)
        self.assertRegex(rec, r"submits=[1-9]")


# ---- the installer's --m3-gpu-experiment ----------------------------------------------------

try:
    import test_m3_flow as flow
except ImportError:  # pragma: no cover
    flow = None

SRC = (HERE.parent / "install-aurora-sep.sh").read_text()
SCRIPTS = re.findall(r'^  "(air-gpu-[a-z]+\.sh) ([0-9a-f]{64})"$', SRC, re.M)


class GpuExperimentReleaseTest(unittest.TestCase):
    def test_the_installer_names_these_scripts(self):
        # The release ships these files as assets: the checksums must be the sources'.
        self.assertEqual(sorted(n for n, _ in SCRIPTS), ["air-gpu-collect.sh", "air-gpu-job.sh", "air-gpu-oneshot.sh"])
        for name, sha in SCRIPTS:
            with self.subTest(name=name):
                self.assertEqual(hashlib.sha256((TOOLS / name).read_bytes()).hexdigest(), sha,
                                 f"update {name}'s sha256 in M3_GPU_SCRIPTS")

    def test_mesa_placeholder(self):
        mesa = re.search(r'^M3_GPU_MESA_PACKAGE="([^"]*)"$', SRC, re.M).group(1)
        prefix = re.search(r'^M3_GPU_MESA_PREFIX="([^"]*)"$', SRC, re.M).group(1)
        # Empty until the G15G Mesa build exists; then both are set, the package as "file sha256".
        if mesa or prefix:
            self.assertRegex(mesa, r"^\S+\.pkg\.tar\.zst [0-9a-f]{64}$")
            self.assertTrue(prefix.startswith("/"), prefix)

    def test_off_by_default(self):
        self.assertRegex(SRC, r"(?m)^M3_GPU_EXPERIMENT=0$")


Base = flow.M3FlowBase if flow else unittest.TestCase


class GpuExperimentFlagTest(Base):
    def setUp(self):
        if flow is None:
            self.skipTest("test_m3_flow is needed")
        super().setUp()
        for name, _ in SCRIPTS:
            shutil.copy(TOOLS / name, self.tmp / "pkgs" / name)
        self.bin = self.tmp / "usr-local-bin"
        # --uninstall runs the installed air-gpu-oneshot.sh --disarm, which logs.
        (self.tmp / "bin/logger").write_text("#!/bin/sh\nexit 0\n")
        (self.tmp / "bin/logger").chmod(0o755)

    def sh(self, body, check=True, flag=1):
        return self.run_sh(f"M3_GPU_BIN='{self.bin}'\nM3_GPU_EXPERIMENT={flag}\n{body}", check=check)

    def test_air_gets_the_scripts_and_nothing_is_armed(self):
        self.mac("j613")
        before = self.boot.read_bytes()
        proc = self.sh("M3_TRY=0\ninstall_all")
        for name, _ in SCRIPTS:
            with self.subTest(name=name):
                self.assertIn(name, self.downloaded())
                self.assertTrue(os.access(self.bin / name, os.X_OK))
                self.assertEqual((self.bin / name).read_bytes(), (TOOLS / name).read_bytes())
        self.assertIn("--m3-gpu-experiment: installing the M3 Air GPU experiment's scripts", proc.stderr)
        self.assertIn("Nothing is armed", proc.stdout)
        self.assertIn("no G15G Mesa prefix yet", proc.stdout)
        self.assertIn("does not hand the GPU over", proc.stdout)
        self.assertIn("pacman -S --needed --noconfirm python vulkan-icd-loader", self.log())
        # The kernel-only Air keeps its boot.bin; nothing in /etc/m1n1.conf.
        self.assertEqual(self.boot.read_bytes(), before)
        self.assertFalse(self.m1n1_conf.exists())
        rec = (self.state / "m3-gpu-experiment").read_text().splitlines()
        self.assertEqual(sorted(l.split()[1] for l in rec), sorted(n for n, _ in SCRIPTS))

        # A plain rerun keeps them and says so.
        proc = self.sh("M3_TRY=0\ninstall_all", flag=0)
        self.assertIn("Keeping the M3 Air GPU experiment's scripts", proc.stdout)
        self.assertTrue((self.bin / "air-gpu-oneshot.sh").exists())

        self.sh("uninstall_all", flag=0)
        for name, _ in SCRIPTS:
            self.assertFalse((self.bin / name).exists(), name)
        self.assertFalse(self.state.exists())

    def test_with_the_handoff(self):
        self.mac("j613")
        self.sh("M3_TRY=1\ninstall_all")
        self.assertTrue((self.bin / "air-gpu-collect.sh").exists())
        self.assertEqual((self.state / "m3-mode").read_text().split()[0], "handoff")

    def test_other_macs_get_nothing(self):
        for board in ("j516s", "j314s", "j504"):
            with self.subTest(board=board):
                self.mac(board)
                before = self.boot.read_bytes()
                proc = self.sh("M3_TRY=0\ninstall_all", check=False)
                self.assertNotEqual(proc.returncode, 0)
                self.assertIn("--m3-gpu-experiment is for the M3 MacBook Air (j613, j615) only", proc.stderr)
                self.assertIn("Nothing was installed", proc.stderr)
                self.assertEqual(self.downloaded(), [])
                self.assertEqual(self.boot.read_bytes(), before)
                self.assertFalse(self.bin.exists())

    def test_a_changed_script_is_refused(self):
        self.mac("j613")
        (self.tmp / "pkgs/air-gpu-job.sh").write_text("#!/bin/sh\necho changed\n")
        proc = self.sh("M3_TRY=0\ninstall_all", check=False)
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("air-gpu-job.sh does not match its published checksum", proc.stderr)
        self.assertFalse(self.bin.exists())
        self.assertNotIn("pacman -U", self.log())

    def test_the_mesa_package(self):
        self.mac("j613")
        name = "mesa-aurora-g15g-26.3.0-1-aarch64.pkg.tar.zst"
        root = self.tmp / "root-mesa"
        (root / "opt/aurora-mesa-g15g/lib").mkdir(parents=True)
        (root / ".PKGINFO").write_text("pkgname = mesa-aurora-g15g\npkgver = 26.3.0-1\n")
        subprocess.run(["bsdtar", "--zstd", "-cf", str(self.tmp / "pkgs" / name), "-C", str(root), ".PKGINFO", "opt"],
                       check=True)
        sha = hashlib.sha256((self.tmp / "pkgs" / name).read_bytes()).hexdigest()
        proc = self.sh(f'M3_GPU_MESA_PACKAGE="{name} {sha}"\nM3_GPU_MESA_PREFIX=/opt/aurora-mesa-g15g\n'
                       "M3_TRY=0\ninstall_all")
        self.assertIn(name, self.downloaded())
        self.assertRegex(self.log(), rf"pacman -U .*{re.escape(name)}")
        self.assertIn("The G15G Mesa prefix for air-gpu-job.sh: /opt/aurora-mesa-g15g", proc.stdout)
        self.assertIn("mesa mesa-aurora-g15g", (self.state / "m3-gpu-experiment").read_text())
        self.sh("uninstall_all", flag=0)
        self.assertIn("pacman -Rns --noconfirm mesa-aurora-g15g", self.log())

    def test_a_malformed_mesa_entry_stops_first(self):
        self.mac("j613")
        proc = self.sh('M3_GPU_MESA_PACKAGE="PENDING"\nM3_TRY=0\ninstall_all', check=False)
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("packaging mistake", proc.stderr)
        self.assertEqual(self.downloaded(), [])

    def test_without_the_flag_nothing_changes(self):
        self.mac("j613")
        self.sh("M3_TRY=0\ninstall_all", flag=0)
        self.assertFalse([d for d in self.downloaded() if d.startswith("air-gpu-")])
        self.assertFalse(self.bin.exists())
        self.assertFalse((self.state / "m3-gpu-experiment").exists())

    def test_options(self):
        # The option block alone, with die and the actions stubbed: nothing is installed here.
        block = SRC[SRC.index("# --m3-handoff and --m3-gpu-experiment go with an install"):
                    SRC.index('if preflight_needed "${1:-}"')]
        for args, want in [("--m3-gpu-experiment", "ok 0 1 -"),
                           ("--m3-handoff --m3-gpu-experiment", "ok 1 1 -"),
                           ("--m3-gpu-experiment --read-only", "ok 0 1 --read-only"),
                           ("--m3-gpu-experiment --uninstall", "error: --m3-gpu-experiment goes with an install"),
                           ("--m3-report --m3-gpu-experiment", "error: --m3-gpu-experiment goes with an install"),
                           ("--uninstall", "ok 0 0 --uninstall")]:
            with self.subTest(args=args):
                script = ('die() { echo "error: $*"; exit 1; }\nM3_TRY=0\nM3_GPU_EXPERIMENT=0\n'
                          f"set -- {args}\n{block}\necho \"ok $M3_TRY $M3_GPU_EXPERIMENT ${{1:--}}\"\n")
                out = subprocess.run(["bash", "-c", script], capture_output=True, text=True).stdout
                self.assertTrue(out.startswith(want), out)

if __name__ == "__main__":
    unittest.main()
