# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_APPLE_CENTAURI) += apple_centauri.o
apple_centauri-y := centauri_pci.o centauri_ipc.o
apple_centauri-$(CONFIG_APPLE_CENTAURI_WIFI) += centauri_wifi.o
