# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_DRM_ACCEL_ANE) += ane.o ane_t6021.o

ane-y := \
	ane_drv.o \
	ane_tm.o \
	ane_dart.o \
	ane_boost.o

ane_t6021-y := \
	ane_t6021_rtclient_main.o \
	ane_t6021_fwload.o \
	ane_t6021_boot.o
